"""Measure ensemble disagreement on ordinary, model-steered, and control rollouts.

Prerequisites: train two pilot members with ``python -m ldr.train_ensemble`` (expand
to five with ``--members 5``), and run ``python diagnostics/dream_fidelity.py --collect``
to create the cached test-track rollouts.  The default behavior model and driver are
``runs/mdnrnn/best.pt`` and ``runs/dream_v3/best.pt``. Run a repaired-controller comparison by
passing its checkpoint with ``--controller`` and the corresponding cached rollout file
with ``--store``.

At each transition every member receives the same latent/action input and maintains its
own recurrent state. The behavior trajectory is generated by the selected single behavior
model using deterministic mixture-mean transitions. Reported epistemic disagreement is the
maximum pairwise L2 distance among deterministic next-latent means. MDN component spread is reported
separately as aleatoric scale and is never included in that distance.
"""
from __future__ import annotations

import argparse
import csv
import gzip
import json
import time
from pathlib import Path

import matplotlib
import numpy as np
import torch
from scipy.stats import spearmanr

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from ldr.check_dream import load_mdnrnn
from ldr.config import DATA, REPORTS, RUNS, C
from ldr.controller import act_batched
from ldr.ensemble import MDNRNNEnsemble
from ldr.envs import make_env
from ldr.mdnrnn import mdn_mean


def first_off_run(onroad, run=20):
    count = 0
    for i, on in enumerate(onroad):
        count = 0 if on else count + 1
        if count == run:
            return i - run + 1
    return None


def bootstrap_ci(values, statistic=np.mean, reps=2000, seed=0):
    values = np.asarray(values, float)
    if len(values) < 2:
        return [None, None]
    rng = np.random.default_rng(seed)
    sample = [statistic(rng.choice(values, len(values), replace=True)) for _ in range(reps)]
    sample = np.asarray(sample, float)
    sample = sample[np.isfinite(sample)]
    if not len(sample):
        return [None, None]
    return [float(np.quantile(sample, .025)), float(np.quantile(sample, .975))]


def bootstrap_difference_ci(left, right, reps=2000, seed=0):
    left, right = np.asarray(left, float), np.asarray(right, float)
    if not len(left) or not len(right):
        return [None, None]
    rng = np.random.default_rng(seed)
    draws = [rng.choice(left, len(left), replace=True).mean()
             - rng.choice(right, len(right), replace=True).mean() for _ in range(reps)]
    return [float(np.quantile(draws, .025)), float(np.quantile(draws, .975))]


def spearman_or_none(x, y):
    result = spearmanr(x, y).statistic
    return float(result) if np.isfinite(result) else None


def _env_replay(seed, prefix, actions):
    """Replay generated actions from the exact logged test-track start state."""
    env = make_env()
    _obs, _ = env.reset(seed=int(seed))
    prefix_return = 0.0
    for action in prefix:
        _obs, r, term, trunc, _ = env.step(action)
        prefix_return += float(r)
        if term or trunc:
            env.close()
            return None
    rewards, onroad = [], []
    for action in actions:
        _obs, r, term, trunc, _ = env.step(action)
        rewards.append(float(r))
        onroad.append(any(len(w.tiles) > 0 for w in env.unwrapped.car.wheels))
        if term or trunc:
            break
    env.close()
    return np.asarray(rewards), np.asarray(onroad, bool), prefix_return


def _ordinary_validation_windows(count, horizon, seed):
    """Uniform held-out dataset windows; do not select them by their road outcomes."""
    data = np.load(DATA / "latents.npz")
    onroad = np.load(DATA / "latents_onroad.npy")
    eligible = [int(e) for e in np.flatnonzero(data["is_val"])
                if int(data["ep_len"][e]) >= horizon + 1]
    if not eligible:
        return []
    rng = np.random.default_rng(seed)
    chosen = rng.choice(eligible, min(count, len(eligible)), replace=False)
    result = []
    for e in chosen:
        e = int(e)
        length = int(data["ep_len"][e])
        t0 = int(rng.integers(1, length - horizon + 1))
        os, ac = int(data["obs_start"][e]), int(data["act_start"][e])
        result.append(({"mu": data["mu"][os:os + length + 1].copy(),
                        "act": data["actions"][ac:ac + length].copy(),
                        "rew": data["rewards"][ac:ac + length].copy(),
                        "onroad": onroad[ac:ac + length].astype(bool).copy(),
                        "seed": -(e + 1)}, t0, horizon))
    return result


@torch.no_grad()
def _rollout(ensemble, behavior_model, episode, t0, horizon, theta, category, seed):
    device = next(ensemble.parameters()).device
    mu = torch.from_numpy(episode["mu"]).to(device)
    acts = torch.from_numpy(episode["act"]).to(device)
    states = [m.initial_state(1, device) for m in ensemble.members]
    behavior_state = behavior_model.initial_state(1, device)
    # Shared real history, separate member-specific recurrent states.
    for k in range(t0):
        z_k = mu[k:k + 1]
        a_k = acts[k:k + 1]
        warm = ensemble.step(z_k, a_k, states)
        states = warm.states
        *_, behavior_state = behavior_model.step(z_k, a_k, behavior_state)
    z = mu[t0:t0 + 1]
    rng = np.random.default_rng(seed)
    rows, action_seq = [], []
    for step in range(horizon):
        if category in ("ordinary", "onset_open_loop"):
            action = acts[t0 + step:t0 + step + 1]
        elif category == "controller":
            h = behavior_state[0][0]
            action = act_batched(theta, z, h)
        elif category == "constant":
            action = torch.tensor([[0.0, 0.5, 0.0]], dtype=torch.float32, device=device)
        elif category == "random":
            action = torch.tensor([[rng.uniform(-1, 1), rng.uniform(0, 1),
                                    rng.uniform(0, 1)]], dtype=torch.float32, device=device)
        else:
            raise ValueError(category)
        pred = ensemble.step(z, action, states, return_on=all(m.has_on for m in ensemble.members))
        base = behavior_model.step(z, action, behavior_state)
        behavior_state = base[5]
        base_reward = float(base[3][0].cpu())
        disagreement = ensemble.disagreement(pred.next_latent)[0]
        for model_id in range(ensemble.n_members):
            rows.append({"timestep": step, "model_id": model_id,
                         "predicted_latent": pred.next_latent[model_id, 0].cpu().tolist(),
                         "ensemble_disagreement": float(disagreement.cpu()),
                         "aleatoric_scale": float(ensemble.aleatoric_scale(
                             pred.means[:, 0:1], pred.log_scales[:, 0:1],
                             pred.logits[:, 0:1])[model_id, 0].cpu()),
                         "predicted_reward": float(pred.rewards[model_id, 0].cpu()),
                         "behavior_model_reward": base_reward,
                         "predicted_road_probability": (float(torch.sigmoid(pred.on_logits[
                             model_id, 0]).cpu()) if pred.on_logits is not None else None),
                         "action": action[0].cpu().tolist()})
        action_seq.append(action[0].cpu().numpy())
        z, states = mdn_mean(base[0], base[1]), pred.states
    return rows, np.asarray(action_seq, np.float32)


def _trajectory_stats(trajectories):
    out = {}
    for category in sorted({t["category"] for t in trajectories}):
        group = [t for t in trajectories if t["category"] == category]
        vals = np.asarray([t["mean_disagreement"] for t in group], float)
        bins = {}
        for lo, hi in ((0, 20), (20, 40), (40, 70), (70, 100)):
            v = [float(x) for t in group for x in t["disagreement_by_step"][lo:hi]]
            if v:
                bins[f"{lo}-{hi}"] = {"mean": float(np.mean(v)), "median": float(np.median(v)),
                                       "q10": float(np.quantile(v, .1)),
                                       "q90": float(np.quantile(v, .9)), "n_steps": len(v)}
        out[category] = {"trajectories": len(group), "mean_disagreement": float(vals.mean()),
                         "median_disagreement": float(np.median(vals)),
                         "q10": float(np.quantile(vals, .1)), "q90": float(np.quantile(vals, .9)),
                         "mean_ci95_bootstrap": bootstrap_ci(vals), "timestep_bins": bins}
    return out


@torch.no_grad()
def _inference_benchmark(ensemble, repetitions=250):
    device = next(ensemble.parameters()).device
    z, action = torch.zeros(1, C.z_dim, device=device), torch.zeros(1, C.a_dim, device=device)
    single = ensemble.members[0]
    state = single.initial_state(1, device)
    states = [m.initial_state(1, device) for m in ensemble.members]
    for _ in range(20):
        single.step(z, action, state)
        ensemble.step(z, action, states)
    def sync():
        if device.type == "cuda":
            torch.cuda.synchronize(device)
        elif device.type == "mps":
            torch.mps.synchronize()
    sync()
    start = time.perf_counter()
    for _ in range(repetitions):
        single.step(z, action, state)
    sync()
    one = time.perf_counter() - start
    start = time.perf_counter()
    for _ in range(repetitions):
        ensemble.step(z, action, states)
    sync()
    many = time.perf_counter() - start
    return {"repetitions": repetitions, "single_model_ms_per_step": one * 1000 / repetitions,
            "ensemble_ms_per_step": many * 1000 / repetitions,
            "relative_overhead_factor": many / one if one else None}


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--ensemble", type=Path, default=RUNS / "mdnrnn_ensemble")
    p.add_argument("--behavior-model", type=Path, default=RUNS / "mdnrnn" / "best.pt",
                   help="single MDN-RNN that generates the imagined state and controller actions")
    p.add_argument("--controller", type=Path, default=RUNS / "dream_v3" / "best.pt")
    p.add_argument("--store", type=Path, default=DATA / "dream_failure" / "rollouts_dream_v3.npz")
    p.add_argument("--episodes", type=int, default=100)
    p.add_argument("--simulator-replays", type=int, default=25,
                   help="maximum model-controller action sequences to replay in the simulator")
    p.add_argument("--seed", type=int, default=731)
    p.add_argument("--out", type=Path, default=REPORTS / "ensemble_uncertainty")
    p.add_argument("--device", default="cpu")
    a = p.parse_args()
    started = time.perf_counter()
    ensemble = MDNRNNEnsemble.load(a.ensemble, a.device)
    behavior_model = load_mdnrnn(a.behavior_model, a.device).eval()
    training_config_path = a.ensemble / "training_config.json"
    training_config = (json.loads(training_config_path.read_text())
                       if training_config_path.exists() else {})
    raw = np.load(a.store)
    tracks = []
    for start, length, seed in zip(raw["start"], raw["length"], raw["seed"]):
        sl = slice(int(start), int(start + length))
        tracks.append({k: raw[k][sl].copy() for k in ("mu", "logvar", "act", "rew", "onroad")})
        tracks[-1]["seed"] = int(seed)
    theta = torch.load(a.controller, map_location=a.device, weights_only=False)["theta"]
    theta = torch.as_tensor(np.asarray(theta), dtype=torch.float32, device=a.device).reshape(1, -1)

    trajectories, per_step = [], []
    # Use the existing onset criterion and a fixed 30-step lead in all categories.
    selected = []
    for i, ep in enumerate(tracks[:a.episodes]):
        onset = first_off_run(ep["onroad"])
        if onset is None:
            continue
        t0 = onset + 1 - 30
        horizon = min(100, len(ep["act"]) - t0)
        if t0 < 1 or horizon < 20:
            continue
        selected.append((i, ep, t0, horizon))
    replay_rng = np.random.default_rng(a.seed)
    replay_ids = set(replay_rng.choice([i for i, *_ in selected],
                                      min(a.simulator_replays, len(selected)),
                                      replace=False).tolist()) if selected else set()

    # Independent normal baseline from held-out recorded trajectories, sampled without
    # conditioning on whether they later leave the road.
    ordinary = _ordinary_validation_windows(a.episodes, 100, a.seed)
    for i, (ep, t0, horizon) in enumerate(ordinary):
        rows, _ = _rollout(ensemble, behavior_model, ep, t0, horizon, theta, "ordinary", a.seed + i)
        disagree = np.asarray([r["ensemble_disagreement"] for r in rows[::ensemble.n_members]])
        pred_return = float(sum(r["behavior_model_reward"] for r in rows[::ensemble.n_members]))
        real_return = float(ep["rew"][t0:t0 + horizon].sum())
        actual_on = ep["onroad"][t0:t0 + horizon]
        trajectory_id = f"validation-{abs(ep['seed'])}-ordinary"
        fail = first_off_run(actual_on) is not None
        for row in rows:
            row.update({"trajectory_id": trajectory_id, "category": "ordinary",
                        "eventual_simulator_failure": fail, "model_predicted_return": pred_return,
                        "real_return": real_return,
                        "actual_simulator_road_status": bool(actual_on[row["timestep"]])})
            per_step.append(row)
        trajectories.append({"trajectory_id": trajectory_id, "seed": ep["seed"],
                             "category": "ordinary", "mean_disagreement": float(disagree.mean()),
                             "disagreement_by_step": disagree.tolist(),
                             "model_predicted_return": pred_return, "real_return": real_return,
                             "model_overoptimism": pred_return - real_return,
                             "eventual_simulator_failure": fail})

    for i, ep, t0, horizon in selected:
        for category in ("onset_open_loop", "controller", "constant", "random"):
            rows, actions = _rollout(ensemble, behavior_model, ep, t0, horizon, theta, category,
                                     a.seed + i * 17 + len(category))
            disagree = np.asarray([r["ensemble_disagreement"] for r in rows[::ensemble.n_members]])
            pred_return = float(sum(r["behavior_model_reward"] for r in rows[::ensemble.n_members]))
            if category == "onset_open_loop":
                real_rewards = ep["rew"][t0:t0 + horizon]
                real_on = ep["onroad"][t0:t0 + horizon]
                real_return, actual_on = float(real_rewards.sum()), real_on
            elif category in ("controller", "constant", "random") and i in replay_ids:
                replay = _env_replay(ep["seed"], ep["act"][:t0], actions)
                if replay is None:
                    real_return, actual_on = None, None
                else:
                    rr, actual_on, _ = replay
                    real_return = float(rr.sum())
            else:
                real_return, actual_on = None, None
            fail = bool(actual_on is not None and first_off_run(actual_on) is not None)
            trajectory_id = f"track-{ep['seed']}-{category}"
            for row in rows:
                row.update({"trajectory_id": trajectory_id, "category": category,
                            "eventual_simulator_failure": fail if actual_on is not None else None,
                            "model_predicted_return": pred_return,
                            "real_return": real_return,
                            "actual_simulator_road_status": (bool(actual_on[row["timestep"]])
                                                             if actual_on is not None and
                                                             row["timestep"] < len(actual_on) else None)})
                per_step.append(row)
            tr = {"trajectory_id": trajectory_id, "seed": ep["seed"], "category": category,
                  "mean_disagreement": float(disagree.mean()),
                  "disagreement_by_step": disagree.tolist(), "model_predicted_return": pred_return,
                  "real_return": real_return, "model_overoptimism": (
                      pred_return - real_return if real_return is not None else None),
                  "eventual_simulator_failure": fail if actual_on is not None else None}
            trajectories.append(tr)
        print(f"processed track {ep['seed']} ({time.perf_counter() - started:.1f}s)", flush=True)

    # Select high predicted-return controller runs by a predeclared top-quartile rule.
    ctrl = [t for t in trajectories if t["category"] == "controller"]
    if ctrl:
        high_n = max(1, int(np.ceil(len(ctrl) * .25)))
        high_runs = sorted(ctrl, key=lambda t: t["model_predicted_return"], reverse=True)[:high_n]
        source_rows = list(per_step)
        for t in high_runs:
            high = {**t, "trajectory_id": t["trajectory_id"] + "-high-return",
                    "category": "high_predicted_return"}
            trajectories.append(high)
            for row in source_rows:
                if row["trajectory_id"] == t["trajectory_id"]:
                    per_step.append({**row, "trajectory_id": high["trajectory_id"],
                                     "category": "high_predicted_return"})

    matched = [t for t in trajectories if t["category"] == "controller" and
               t["real_return"] is not None]
    matched_by_category = {category: [t for t in trajectories if t["category"] == category and
                                      t["real_return"] is not None]
                           for category in ("controller", "constant", "random")}
    over = np.asarray([t["model_overoptimism"] for t in matched], float)
    dis = np.asarray([t["mean_disagreement"] for t in matched], float)
    rho = spearman_or_none(dis, over) if len(matched) >= 3 else None
    def bootstrap_rho(indices):
        indices = indices.astype(int)
        return spearman_or_none(dis[indices], over[indices]) if len(indices) >= 3 else np.nan
    rho_ci = (bootstrap_ci(np.arange(len(matched)), statistic=bootstrap_rho)
              if len(matched) >= 3 else [None, None])
    failure_flags = np.asarray([int(t["eventual_simulator_failure"]) for t in matched])
    def bootstrap_failure_rho(indices):
        indices = indices.astype(int)
        y = failure_flags[indices]
        return (spearman_or_none(dis[indices], y)
                if len(indices) >= 3 and len(np.unique(y)) == 2 else np.nan)
    failure_rho_ci = (bootstrap_ci(np.arange(len(matched)), statistic=bootstrap_failure_rho, seed=1)
                      if len(matched) >= 3 and len(np.unique(failure_flags)) == 2 else [None, None])
    failures = [t for t in matched if t["eventual_simulator_failure"]]
    successes = [t for t in matched if not t["eventual_simulator_failure"]]
    failure_rho = (spearman_or_none(dis, failure_flags)
                   if len(matched) >= 3 and len(failures) and len(successes) else None)
    by_category = {c: [t["mean_disagreement"] for t in trajectories if t["category"] == c]
                   for c in {t["category"] for t in trajectories}}
    failures_all = [t["mean_disagreement"] for t in matched if t["eventual_simulator_failure"]]
    successes_all = [t["mean_disagreement"] for t in matched if not t["eventual_simulator_failure"]]
    category_comparisons = {}
    for label, left, right in (("controller_minus_ordinary", "controller", "ordinary"),
                               ("controller_minus_constant", "controller", "constant"),
                               ("high_return_minus_other_controller", "high_predicted_return", "controller")):
        x, y = by_category.get(left, []), by_category.get(right, [])
        paired = None
        if label == "controller_minus_constant":
            l_by_seed = {t["seed"]: t["mean_disagreement"] for t in ctrl}
            r_by_seed = {t["seed"]: t["mean_disagreement"] for t in trajectories
                         if t["category"] == "constant"}
            paired = [l_by_seed[s] - r_by_seed[s] for s in l_by_seed.keys() & r_by_seed.keys()]
            x, y = [], []
        # For the high-return contrast, remove the duplicated high-return rows from its parent.
        if label == "high_return_minus_other_controller":
            high_ids = {t["trajectory_id"].removesuffix("-high-return") for t in trajectories
                        if t["category"] == "high_predicted_return"}
            y = [t["mean_disagreement"] for t in ctrl if t["trajectory_id"] not in high_ids]
        category_comparisons[label] = {
            "left_n": len(paired) if paired is not None else len(x),
            "right_n": len(paired) if paired is not None else len(y),
            "paired": paired is not None,
            "mean_difference": (float(np.mean(paired)) if paired is not None and paired else
                                float(np.mean(x) - np.mean(y)) if x and y else None),
            "bootstrap_ci95": (bootstrap_ci(paired) if paired is not None else
                               bootstrap_difference_ci(x, y))}
    category_comparisons["matched_failure_minus_success"] = {
        "left_n": len(failures_all), "right_n": len(successes_all),
        "mean_difference": (float(np.mean(failures_all) - np.mean(successes_all))
                            if failures_all and successes_all else None),
        "bootstrap_ci95": bootstrap_difference_ci(failures_all, successes_all)}
    high_ids = {t["trajectory_id"].removesuffix("-high-return") for t in trajectories
                if t["category"] == "high_predicted_return"}
    high_matched = [t for t in matched if t["trajectory_id"] in high_ids]
    high_over = np.asarray([t["model_overoptimism"] for t in high_matched], float)
    high_other_over = np.asarray([t["model_overoptimism"] for t in matched
                                  if t["trajectory_id"] not in high_ids], float)
    policy_overoptimism = {
        category: {"n": len(group),
                   "mean": (float(np.mean([t["model_overoptimism"] for t in group])) if group else None),
                   "median": (float(np.median([t["model_overoptimism"] for t in group])) if group else None),
                   "ci95_bootstrap": bootstrap_ci([t["model_overoptimism"] for t in group])}
        for category, group in matched_by_category.items()}
    matched_policy_comparisons = {}
    ctrl_over = {t["seed"]: t["model_overoptimism"] for t in matched_by_category["controller"]}
    for category in ("constant", "random"):
        control_over = {t["seed"]: t["model_overoptimism"]
                        for t in matched_by_category[category]}
        differences = [ctrl_over[s] - control_over[s]
                       for s in ctrl_over.keys() & control_over.keys()]
        matched_policy_comparisons[f"controller_minus_{category}_overoptimism"] = {
            "n": len(differences), "mean_difference": float(np.mean(differences)) if differences else None,
            "bootstrap_ci95": bootstrap_ci(differences, seed=3)}
    controller_temporal = {}
    for (left, lo, hi), (right, rlo, rhi) in ((("0-20", 0, 20), ("20-40", 20, 40)),
                                              (("20-40", 20, 40), ("40-70", 40, 70)),
                                              (("40-70", 40, 70), ("70-100", 70, 100))):
        paired_delta = []
        for t in ctrl:
            values = t["disagreement_by_step"]
            if len(values) >= rhi:
                paired_delta.append(float(np.mean(values[rlo:rhi]) - np.mean(values[lo:hi])))
        controller_temporal[f"{right}_minus_{left}"] = {
            "n": len(paired_delta), "mean_difference": float(np.mean(paired_delta)) if paired_delta else None,
            "bootstrap_ci95": bootstrap_ci(paired_delta, seed=2)}
    summary = {"configuration": {"members": ensemble.n_members, "seeds": ensemble.seeds,
                                 "disagreement": "max pairwise L2 distance between deterministic MDN mixture means",
                                 "behavior_model": str(a.behavior_model),
                                 "behavior_rollout": "deterministic mixture mean",
                                 "episode_start": "30 steps before first 20-step off-road run",
                                 "simulator_failure": "at least 20 consecutive off-road transitions within the window",
                                 "high_return_selection": "top ceil(25% of controller runs), fixed before inspection",
                                 "cumulative_member_training_seconds": training_config.get(
                                     "total_training_seconds"),
                                 "latest_training_invocation_wall_seconds": training_config.get(
                                     "current_invocation_wall_seconds"),
                                 "training_parallel_members": training_config.get(
                                     "parallel_members")},
               "trajectory_statistics": _trajectory_stats(trajectories),
               "category_comparisons": category_comparisons,
               "controller_temporal_changes": controller_temporal,
               "matched_policy_overoptimism": policy_overoptimism,
               "matched_policy_comparisons": matched_policy_comparisons,
               "inference_benchmark": _inference_benchmark(ensemble),
               "matched_controller_analysis": {"n": len(matched),
                   "spearman_disagreement_overoptimism": rho, "bootstrap_ci95_rho": rho_ci,
                   "spearman_disagreement_failure": failure_rho,
                   "bootstrap_ci95_failure_rho": failure_rho_ci,
                   "high_predicted_return_matched": {"n": len(high_matched),
                       "mean_model_overoptimism": float(high_over.mean()) if len(high_over) else None,
                       "median_model_overoptimism": float(np.median(high_over)) if len(high_over) else None,
                       "model_overoptimism_ci95": bootstrap_ci(high_over),
                       "simulator_failures": sum(t["eventual_simulator_failure"] for t in high_matched),
                       "overoptimism_minus_other_controller": (
                           float(high_over.mean() - high_other_over.mean())
                           if len(high_over) and len(high_other_over) else None),
                       "overoptimism_difference_ci95": bootstrap_difference_ci(
                           high_over, high_other_over)},
                   "failure_mean_disagreement": (float(np.mean([t["mean_disagreement"] for t in failures]))
                                                 if failures else None),
                   "success_mean_disagreement": (float(np.mean([t["mean_disagreement"] for t in successes]))
                                                  if successes else None),
                   "exploited_mean_disagreement": (float(np.mean([t["mean_disagreement"] for t in matched
                       if t["eventual_simulator_failure"] and t["model_overoptimism"] > 0]))
                       if any(t["eventual_simulator_failure"] and t["model_overoptimism"] > 0
                              for t in matched) else None),
                   "failure_n": len(failures), "success_n": len(successes)},
               "runtime_seconds": time.perf_counter() - started}

    a.out.mkdir(parents=True, exist_ok=True)
    (a.out / "results.json").write_text(json.dumps({"summary": summary,
                                                     "trajectories": trajectories}, indent=1) + "\n")
    with gzip.open(a.out / "per_step.csv.gz", "wt", newline="") as f:
        fields = list(per_step[0]) if per_step else []
        writer = csv.DictWriter(f, fieldnames=fields)
        if fields:
            writer.writeheader()
            for row in per_step:
                writer.writerow({**row, "predicted_latent": json.dumps(row["predicted_latent"]),
                                 "action": json.dumps(row["action"])})

    colors = {"ordinary": "#555555", "onset_open_loop": "#a0a0a0", "controller": "#2468a2",
              "high_predicted_return": "#cf4b28", "constant": "#31936a", "random": "#9467bd"}
    plt.figure(figsize=(8, 4.8))
    for category, color in colors.items():
        group = [t for t in trajectories if t["category"] == category]
        if not group:
            continue
        width = min(len(t["disagreement_by_step"]) for t in group)
        x = np.asarray([t["disagreement_by_step"][:width] for t in group])
        mean, lo, hi = x.mean(0), np.quantile(x, .25, axis=0), np.quantile(x, .75, axis=0)
        plt.plot(mean, label=f"{category} (n={len(group)})", color=color)
        plt.fill_between(np.arange(width), lo, hi, alpha=.16, color=color)
    failed = [t for t in ctrl if t["eventual_simulator_failure"] is True]
    if failed:
        width = min(len(t["disagreement_by_step"]) for t in failed)
        plt.plot(np.mean([t["disagreement_by_step"][:width] for t in failed], axis=0),
                 color="#d62728", linestyle="--", label=f"controller, simulator failure (n={len(failed)})")
    plt.xlabel("imagined timestep")
    plt.ylabel("max pairwise L2 disagreement (mixture means)")
    plt.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(a.out / "disagreement_by_timestep.png", dpi=160)
    plt.close()

    plt.figure(figsize=(6.5, 4.8))
    policy_colors = {"controller": "#2468a2", "constant": "#31936a", "random": "#9467bd"}
    for category, group in matched_by_category.items():
        for outcome, marker, label in ((True, "x", f"{category}, failed"),
                                       (False, "o", f"{category}, no failure")):
            subset = [t for t in group if t["eventual_simulator_failure"] is outcome]
            if subset:
                plt.scatter([t["mean_disagreement"] for t in subset],
                            [t["model_overoptimism"] for t in subset],
                            c=policy_colors[category], marker=marker, alpha=.75, label=label)
    plt.axhline(0, color="black", linewidth=.8)
    plt.xlabel("mean ensemble disagreement over imagined window")
    plt.ylabel("model overoptimism (predicted return − real return)")
    plt.title(f"Spearman ρ={rho:.2f}" if rho is not None else "Too few matched replays for correlation")
    plt.legend(fontsize=7)
    plt.tight_layout()
    plt.savefig(a.out / "disagreement_vs_overoptimism.png", dpi=160)
    plt.close()

    if matched:
        plt.figure(figsize=(6.5, 4.8))
        real_returns = np.asarray([t["real_return"] for t in matched])
        predicted_returns = np.asarray([t["model_predicted_return"] for t in matched])
        points = plt.scatter(real_returns, predicted_returns,
                             c=[t["mean_disagreement"] for t in matched], cmap="viridis",
                             edgecolors="black", linewidths=.3)
        bounds = [min(real_returns.min(), predicted_returns.min()),
                  max(real_returns.max(), predicted_returns.max())]
        plt.plot(bounds, bounds, color="black", linestyle="--", linewidth=1)
        plt.colorbar(points, label="mean ensemble disagreement")
        plt.xlabel("real simulator return (matched actions)")
        plt.ylabel("behavior model predicted return")
        plt.tight_layout()
        plt.savefig(a.out / "predicted_vs_real_return.png", dpi=160)
        plt.close()
    lines = ["# Ensemble epistemic uncertainty experiment", "",
             f"- Members: {ensemble.n_members}; seeds: {ensemble.seeds}",
             (f"- Cumulative member training: "
              f"{training_config.get('total_training_seconds', 'not recorded')} seconds"),
             (f"- Latest training invocation wall time: "
              f"{training_config.get('current_invocation_wall_seconds', 'not recorded')} seconds "
              f"with {training_config.get('parallel_members', 'unknown')} concurrent members"),
             (f"- Inference benchmark: {summary['inference_benchmark']['single_model_ms_per_step']:.3f} ms/model step; "
              f"{summary['inference_benchmark']['ensemble_ms_per_step']:.3f} ms/ensemble step "
              f"({summary['inference_benchmark']['relative_overhead_factor']:.2f}x)"),
             "- Disagreement: maximum pairwise L2 distance between deterministic MDN mixture means.",
             "- Aleatoric scale is recorded separately from epistemic disagreement.", "",
             "## Disagreement by trajectory category", "",
             "| Category | Trajectories | Mean (95% bootstrap CI) | Median | 10th percentile | 90th percentile |",
             "|---|---:|---:|---:|---:|---:|"]
    for category, values in summary["trajectory_statistics"].items():
        lines.append(f"| {category} | {values['trajectories']} | {values['mean_disagreement']:.4f} "
                     f"[{values['mean_ci95_bootstrap']}] | "
                     f"{values['median_disagreement']:.4f} | {values['q10']:.4f} | {values['q90']:.4f} |")
    lines += ["", "Timestep-band disagreement summaries:", ""]
    for category, values in summary["trajectory_statistics"].items():
        lines.append(f"**{category}**")
        lines.append("")
        lines.append("| Timestep | Mean | Median | 10th percentile | 90th percentile | Steps |")
        lines.append("|---|---:|---:|---:|---:|---:|")
        for band, stats in values["timestep_bins"].items():
            lines.append(f"| {band} | {stats['mean']:.4f} | {stats['median']:.4f} | "
                         f"{stats['q10']:.4f} | {stats['q90']:.4f} | {stats['n_steps']} |")
        lines.append("")
    lines += ["", "## Matched model and simulator returns", "",
              f"- Matched controller sequences: {len(matched)}",
              f"- Spearman disagreement vs overoptimism: {rho}",
              f"- Bootstrap 95% interval for correlation: {rho_ci}",
              f"- Spearman disagreement vs eventual simulator failure: {failure_rho}",
              f"- Bootstrap 95% interval for failure correlation: {failure_rho_ci}",
                (f"- High predicted-return matched overoptimism: "
                 f"{summary['matched_controller_analysis']['high_predicted_return_matched']['mean_model_overoptimism']} "
                 f"(n={summary['matched_controller_analysis']['high_predicted_return_matched']['n']})"),
              (f"- Mean disagreement, simulator failure / success: "
               f"{summary['matched_controller_analysis']['failure_mean_disagreement']} / "
               f"{summary['matched_controller_analysis']['success_mean_disagreement']}"), "",
              "Matched overoptimism by action policy:", "",
              "| Policy | Matched n | Mean predicted − real return | 95% bootstrap CI |",
              "|---|---:|---:|---:|"]
    for category, stats in policy_overoptimism.items():
        lines.append(f"| {category} | {stats['n']} | {stats['mean']} | {stats['ci95_bootstrap']} |")
    lines += ["", "Paired model-overoptimism differences (positive means the controller exploit gap is larger):", ""]
    for comparison, stats in matched_policy_comparisons.items():
        lines.append(f"- {comparison}: {stats['mean_difference']} (95% bootstrap CI "
                     f"{stats['bootstrap_ci95']}; n={stats['n']}).")
    lines += ["", "Paired change in controller disagreement over time:", ""]
    for period, stats in controller_temporal.items():
        lines.append(f"- {period}: mean difference {stats['mean_difference']}; "
                     f"95% bootstrap CI {stats['bootstrap_ci95']} (n={stats['n']}).")
    lines += ["", "## Interpretation checks", "",
              (f"- CMA controller − ordinary mean disagreement: "
               f"{category_comparisons['controller_minus_ordinary']['mean_difference']} "
               f"(bootstrap 95% CI {category_comparisons['controller_minus_ordinary']['bootstrap_ci95']})."),
              (f"- CMA controller − constant-input mean disagreement: "
               f"{category_comparisons['controller_minus_constant']['mean_difference']} "
               f"(bootstrap 95% CI {category_comparisons['controller_minus_constant']['bootstrap_ci95']})."),
              (f"- High-return vs remaining CMA runs: "
               f"{category_comparisons['high_return_minus_other_controller']['mean_difference']} "
               f"(bootstrap 95% CI {category_comparisons['high_return_minus_other_controller']['bootstrap_ci95']})."),
              (f"- Matched simulator-failure vs success disagreement: "
               f"{(float(np.mean(failures_all) - np.mean(successes_all)) if failures_all and successes_all else None)} "
               f"(bootstrap 95% CI {bootstrap_difference_ci(failures_all, successes_all)})."), "",
              ("Interpret the comparisons only after reviewing sample sizes and the confidence intervals. "
               "The behavior policy follows the selected single model's deterministic mixture-mean rollout; all members "
               "are scored on the same latent/action inputs. This isolates disagreement conditional on one "
               "trajectory and does not claim that the ensemble mean is an optimized control policy."), ""]
    (a.out / "summary.md").write_text("\n".join(lines))
    print(json.dumps(summary, indent=2), flush=True)
    print(f"Wrote ensemble results to {a.out}", flush=True)


if __name__ == "__main__":
    main()
